"""add_paused_reason_to_tasks

Revision ID: e6bee304f3e2
Revises: 91d6e9a3ae78
Create Date: 2026-08-21 18:41:15.318789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6bee304f3e2'
down_revision: Union[str, Sequence[str], None] = '91d6e9a3ae78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('paused_reason', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'paused_reason')
    # ### end Alembic commands ###
